item_1=input("Please enter what you would like to order: ")
item_2=input("Please enter another of your favourite foods: ")
item_3=input("One more for good luck: ")
print("Thank you, You have ordered the following: ")
print(item_1)
print(item_2)
print(item_3)
